name: "Build and deploy to nuget.org"

on:
  push: 
    branches: [ master ]

env:
  PROJECT_PATH: "CommonExtensions/CommonExtensions.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"
  VERSION: 1.1.${{ github.run_number }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: windows-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install .net"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.x"

    - name: "Restore packages"
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: "Build project"
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: "Pack Project"
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: "Push Package"
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.KEY }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate